name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace image:... in docker-compose.yaml with value of file latest_tag.txt
        run: |
          sed -i "s|image:.*|image: $(cat latest_tag.txt)|g" docker-compose.yaml

      - name: Deploy compose
        uses: sulthonzh/docker-remote-deployment-action@v0.1.2-beta
        with:
          remote_docker_host: lestar@lestar.ddns.net
          remote_docker_port: 2831
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          copy_stack_file: true
          deploy_path: /home/lestar/containers/plex-to-letterboxd
          stack_file_name: docker-compose.yaml
          keep_files: 5
          args: up -d --remove-orphans
          docker_registry_username: liamnou
          docker_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
